services:
  ddns-updater:
    image: cloubit\dynamic-dns-updater
    container_name: ddns-updater
    env_file:
        - ./ddns_update.env
    restart: always
    networks:
        - internal

networks:
  internal:
    name: ddns-updater
    driver: bridge
    
